blog/urls.py
from django.urls import path, include
from django.conf import settings
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.all_blogs, name="all_blogs"),
    path("<int:blog_id>/", views.details, name="details"),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('blog/', include('blog.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to="portfolio/images/")
    url = models.URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    blogs = Blog.objects.order_by('date')
    return render(request,"blogs/blogs.html",{'blogs':blogs})

def details(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request,"blogs/details.html",{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, "portfolio/home.html", {'projects':projects})

blog/templates/blogs/blogs.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block content %}
<div class="container text-center">
    <h2>Mahesh written {{blogs.count}} blog{{blogs.count|pluralize}}</h2>
</div>
<div class="card-group">
{% for blog in blogs %}
    <div class="card">
        <div class="card-body">
            <a href="{% url 'blog:details' blog.id %}"><h5 class="card-title">{{blog.title}}</h5></a>
            <p class="card-text">{{blog.description|striptags|truncatechars:100}}</p>
            <p class="card-text"><small class="text-muted">{{blog.date|date:'d M Y'}}</small></p>
        </div>
    </div>
{% endfor %}
</div>
{% endblock %}

blog/templates/blogs/details.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block content %} 
    <div class="container">
        <h2>{{blog.title}}</h2>
        <span>{{blog.date|date:'F jS Y'}}</span>
        <p>{{blog.description|safe}}</p>
    </div>
{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
{% load static %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Mahesh Portfolio</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Mahesh</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% static 'portfolio/MaheshResume.pdf' %}">Resume</a>
            <a class="nav-item nav-link" href="https://www.linkedin.com/in/mahesh811/" target="_blank">Linkdin</a>
            <a class="nav-item nav-link" href="https://twitter.com/_beingmahesh" target="_blank">Twitter</a>
            <a class="nav-item nav-link" href="{% url 'blog:all_blogs' %}">Blog</a>
            </div>
        </div>
    </nav>
    {% block content %} {% endblock %}

    <div class="card">
        <div class="card-header">
            Quote
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
            </blockquote>
        </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block content %} 
<div class="container text-center">
    <h2>Mahesh Portfolio</h2>
</div>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static 'portfolio/BMW.jpg' %}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'portfolio/BMW1.jpg' %}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'portfolio/BMW2.jpg' %}" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<div class="card-group">
{% for project in projects %}
    <div class="card">
        <img class="card-img-top" src="{{project.image.url}}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{project.title}}</h5>
            <p class="card-text">{{project.description}}</p>
            {% if project.url %}
                <a href="{{project.url}}"><p class="card-text"><small class="text-muted">Link</small></p></a>
            {% endif %}
        </div>
    </div>
{% endfor %}
</div>
{% endblock %}